### PR TITLE
(WIP) Fix conda build path

### PR DESCRIPTION
**Pull request by sdvillal**
I will try to coordinate with https://github.com/conda-forge/staged-recipes/pull/10331 and will let you know when this is ready to merge

### CODE REVIEW

**Comment by hmaarrfk** [comment]
This patch is a little off.

In particular the jxr libraries for windows have a prefix `lib`.

See latest in https://github.com/conda-forge/staged-recipes/pull/10331

**Comment by hmaarrfk** [comment]
PR made against your branch @sdvillal

**Comment by sdvillal** [comment]
Thanks @hmaarrfk ! Yeah, I never tried building in windows, so I expected trouble. I will remove the WIP status from this PR once we release the package (I like the suggestion to run the imagecodecs testsuite...).

**Comment by cgohlke** [comment]
Thanks. This will be in the next version.

Does conda-forge have the [lerc 2.1](https://github.com/Esri/lerc) library?

**Comment by hmaarrfk** [comment]
Apparently not
https://github.com/conda-forge/gdal-feedstock/issues/381

Thanks for asking.

**Pull request closed without merging**
